#!/bin/sh
I4J_INSTALL_LOCATION="/opt/pdfstudio10"
cd "$I4J_INSTALL_LOCATION"
ln -sf "$I4J_INSTALL_LOCATION/pdfstudio10" /usr/local/bin/
/bin/echo -e "#!/usr/bin/env xdg-open
[Desktop Entry]
Type=Application
Name=PDF Studio 10
Exec=/bin/sh \"$I4J_INSTALL_LOCATION/pdfstudio10\"
Icon=$I4J_INSTALL_LOCATION/.install4j/pdfstudio10.png
" >> "$I4J_INSTALL_LOCATION/pdfstudio10.desktop"
chmod +x "$I4J_INSTALL_LOCATION/pdfstudio10.desktop"
ln -sf "$I4J_INSTALL_LOCATION/updater" /usr/local/bin/
ln -sf "$I4J_INSTALL_LOCATION/pdfstudiosu" /usr/local/bin/

if [ -f "$I4J_INSTALL_LOCATION/jre/lib/rt.jar.pack" ]; then
  old_pwd200=`pwd`
  cd "$I4J_INSTALL_LOCATION/jre"
  echo "Preparing JRE ..."
  for pack_file in lib/*.jar.pack
  do
    jar_file=`echo "$pack_file" | awk '{ print substr($0,1,length-5) }'`
    bin/unpack200 -r "$pack_file" "$jar_file"
  done
  for pack_file in lib/ext/*.jar.pack
  do
    jar_file=`echo "$pack_file" | awk '{ print substr($0,1,length-5) }'`
    bin/unpack200 -r "$pack_file" "$jar_file"
  done
  bin/java -Xshare:dump >/dev/null 2>&1
  cd "$old_pwd200"
fi
exit 0
